# This is an example .kmdopkg.yml file with some sensible defaults.
# Make sure to check the documentation at https://kumose.cc

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://kumose.cc/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

# å½»åº•ç¦ç”¨ Go ç›¸å…³çŽ¯å¢ƒå˜é‡
env: []

# ç¦ç”¨æ‰€æœ‰å‰ç½®é’©å­ï¼ˆé¿å…è§¦å‘ Go ç›¸å…³æ“ä½œï¼‰
before:
  hooks: []

# å…³é”®ï¼šå½»åº•ç¦ç”¨æž„å»ºæµç¨‹ï¼ˆè§£å†³ "no main function" æŠ¥é”™ï¼‰
builds:
  - skip: true  # æ˜Žç¡®è·³è¿‡è¯¥æž„å»ºç»„
    goos: []    # æ¸…ç©ºæ‰€æœ‰ç›®æ ‡ç³»ç»Ÿï¼Œé¿å…é»˜è®¤ç¼–è¯‘
    goarch: []  # æ¸…ç©ºæ‰€æœ‰ç›®æ ‡æž¶æž„
    env: []     # æ¸…ç©ºæž„å»ºçŽ¯å¢ƒå˜é‡

# ç¦ç”¨ Go æ¨¡å—ç›¸å…³é…ç½®ï¼ˆå½»åº•åˆ‡æ–­ Go å…³è”ï¼‰
gomod:
  enabled: false  # æ˜Žç¡®ç¦ç”¨ Go æ¨¡å—

# å…¶ä»–æ— å…³é…ç½®ç»§ç»­ç¦ç”¨
report_sizes: false
universal_binaries: []
notarize: {}
dockers_v2: []
homebrew_casks: []
nix: []
winget: []
aurs: []
scoops: []
nfpms: []
snapcrafts: []
sboms: []
signs: []
docker_signs: []
milestones: []
announce: []

archives:
  - name_template: >-
      {{- .ProjectName }}-
      {{- .Version }}-any-any-
    formats: [tar.gz]
    files:
      - src: "template/**/*"
      - src: "README.md"
      - src: "LICENSE"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  format: "{{ .SHA }}: {{ .Message }}{{ with .AuthorUsername }} (@{{ . }}){{ end }}"
  filters:
    exclude:
      - "^test:"
      - "^docs:"
      - "^ci:"
      - "merge"

# GitHub Release configuration (Linux exclusive)
release:
  github:
    owner: kumose
    name: kmcmake
  draft: false
  prerelease: false
  make_latest: true
  name_template: "v{{ .Version }} (Linux Exclusive)"
  header: |
    ## Project Template v{{ .Version }} Released ðŸš€
    - Platform: Linux only
    - Format: tar.gz (Linux native support)
    - Architectures: x86_64/aarch64 and others (auto-adapted)
    - Usage: Extract and replace 'changeme' placeholder in template directory
  footer: |
    **Full Changelog**: https://github.com/{{ .Owner }}/{{ .Repo }}/compare/{{ .PreviousTag }}...{{ .Tag }}

    Released by [kmdo pkg](https://github.com/kumose/kmdo).
