# CMake generated Testfile for 
# Source directory: /home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/tests
# Build directory: /home/jeff/github/kumose/kmcmake/test/.work/simd_AVX512/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[base_raw_test]=] "/home/jeff/github/kumose/kmcmake/test/.work/simd_AVX512/tests/base_raw_test")
set_tests_properties([=[base_raw_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/kmcmake/tools/kmcmake_cc_test.cmake;118;add_test;/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/tests/CMakeLists.txt;40;kmcmake_cc_test;/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/tests/CMakeLists.txt;0;")
add_test([=[base_pass_test_1]=] "/home/jeff/github/kumose/kmcmake/test/.work/simd_AVX512/tests/base_pass_test")
set_tests_properties([=[base_pass_test_1]=] PROPERTIES  PASS_REGULAR_EXPRESSION "pass;Passed" _BACKTRACE_TRIPLES "/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/kmcmake/tools/kmcmake_cc_test.cmake;168;add_test;/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/tests/CMakeLists.txt;56;kmcmake_cc_test_ext;/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/tests/CMakeLists.txt;0;")
add_test([=[base_pass_test_2]=] "/home/jeff/github/kumose/kmcmake/test/.work/simd_AVX512/tests/base_pass_test")
set_tests_properties([=[base_pass_test_2]=] PROPERTIES  PASS_REGULAR_EXPRESSION "pass;Passed" _BACKTRACE_TRIPLES "/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/kmcmake/tools/kmcmake_cc_test.cmake;168;add_test;/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/tests/CMakeLists.txt;64;kmcmake_cc_test_ext;/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/tests/CMakeLists.txt;0;")
add_test([=[base_pass_test_foo]=] "/home/jeff/github/kumose/kmcmake/test/.work/simd_AVX512/tests/base_pass_test")
set_tests_properties([=[base_pass_test_foo]=] PROPERTIES  PASS_REGULAR_EXPRESSION "pass;Passed" _BACKTRACE_TRIPLES "/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/kmcmake/tools/kmcmake_cc_test.cmake;168;add_test;/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/tests/CMakeLists.txt;71;kmcmake_cc_test_ext;/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/tests/CMakeLists.txt;0;")
add_test([=[base_pass_test_bar]=] "/home/jeff/github/kumose/kmcmake/test/.work/simd_AVX512/tests/base_pass_test")
set_tests_properties([=[base_pass_test_bar]=] PROPERTIES  PASS_REGULAR_EXPRESSION "pass;Passed;DISABLED" _BACKTRACE_TRIPLES "/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/kmcmake/tools/kmcmake_cc_test.cmake;168;add_test;/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/tests/CMakeLists.txt;79;kmcmake_cc_test_ext;/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/tests/CMakeLists.txt;0;")
add_test([=[base_args_test_fail]=] "/home/jeff/github/kumose/kmcmake/test/.work/simd_AVX512/tests/base_args_test")
set_tests_properties([=[base_args_test_fail]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "[^a-z]Error;ERROR;Failed" _BACKTRACE_TRIPLES "/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/kmcmake/tools/kmcmake_cc_test.cmake;168;add_test;/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/tests/CMakeLists.txt;95;kmcmake_cc_test_ext;/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/tests/CMakeLists.txt;0;")
add_test([=[base_args_test_fail_args]=] "/home/jeff/github/kumose/kmcmake/test/.work/simd_AVX512/tests/base_args_test" "Failed")
set_tests_properties([=[base_args_test_fail_args]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "[^a-z]Error;ERROR;Failed" _BACKTRACE_TRIPLES "/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/kmcmake/tools/kmcmake_cc_test.cmake;168;add_test;/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/tests/CMakeLists.txt;103;kmcmake_cc_test_ext;/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/tests/CMakeLists.txt;0;")
add_test([=[base_args_test_skip_fail]=] "/home/jeff/github/kumose/kmcmake/test/.work/simd_AVX512/tests/base_args_test")
set_tests_properties([=[base_args_test_skip_fail]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "[^a-z]Error;ERROR;Failed" PASS_REGULAR_EXPRESSION "pass;Passed" SKIP_REGULAR_EXPRESSION "[^a-z]Skip;SKIP;Skipped" _BACKTRACE_TRIPLES "/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/kmcmake/tools/kmcmake_cc_test.cmake;168;add_test;/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/tests/CMakeLists.txt;112;kmcmake_cc_test_ext;/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/tests/CMakeLists.txt;0;")
add_test([=[base_args_test_skip]=] "/home/jeff/github/kumose/kmcmake/test/.work/simd_AVX512/tests/base_args_test" "SKIP")
set_tests_properties([=[base_args_test_skip]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "[^a-z]Error;ERROR;Failed" PASS_REGULAR_EXPRESSION "pass;Passed" SKIP_REGULAR_EXPRESSION "[^a-z]Skip;SKIP;Skipped" _BACKTRACE_TRIPLES "/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/kmcmake/tools/kmcmake_cc_test.cmake;168;add_test;/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/tests/CMakeLists.txt;122;kmcmake_cc_test_ext;/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/tests/CMakeLists.txt;0;")
add_test([=[base_args_test_skip_pass]=] "/home/jeff/github/kumose/kmcmake/test/.work/simd_AVX512/tests/base_args_test" "Passed")
set_tests_properties([=[base_args_test_skip_pass]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "[^a-z]Error;ERROR;Failed" PASS_REGULAR_EXPRESSION "pass;Passed" SKIP_REGULAR_EXPRESSION "[^a-z]Skip;SKIP;Skipped" _BACKTRACE_TRIPLES "/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/kmcmake/tools/kmcmake_cc_test.cmake;168;add_test;/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/tests/CMakeLists.txt;133;kmcmake_cc_test_ext;/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/tests/CMakeLists.txt;0;")
add_test([=[base_args_test_skip_diabled]=] "/home/jeff/github/kumose/kmcmake/test/.work/simd_AVX512/tests/base_args_test" "Passed")
set_tests_properties([=[base_args_test_skip_diabled]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "[^a-z]Error;ERROR;Failed" PASS_REGULAR_EXPRESSION "pass;Passed" SKIP_REGULAR_EXPRESSION "[^a-z]Skip;SKIP;Skipped;DISABLED" _BACKTRACE_TRIPLES "/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/kmcmake/tools/kmcmake_cc_test.cmake;168;add_test;/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/tests/CMakeLists.txt;144;kmcmake_cc_test_ext;/home/jeff/github/kumose/kmcmake/test/.work/kmcmake_demo/tests/CMakeLists.txt;0;")
