// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'intro',
    'library',
    'binary',
    'interface',
    'gen',
    {
      type: 'category',
      label: 'Advance',
      "link": {
            "type": "generated-index",
            "title": "Advance configuration"
          },
      items: [
        'advance/dependencies',
        'advance/flags',
        'advance/generated-version',
        'advance/export',
        'advance/cmake',
        'advance/preset'
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      "link": {
            "type": "generated-index",
            "title": "Reference"
          },
      items: [
        'reference/cc_lib',
        'reference/cc_binary',
        'reference/cc_benchmark',
        'reference/cc_test',
        'reference/cc_proto',
      ],
    },
  ],
   
};

export default sidebars;
